name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Semantic Release and plugins
        run: |
          npm install -g semantic-release@23 \
                         conventional-changelog-conventionalcommits@7 \
                         @semantic-release/release-notes-generator@13 \
                         @semantic-release/commit-analyzer@12 \
                         @semantic-release/git@10 \
                         @semantic-release/exec@6

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
